# Generated by Django 2.2.2 on 2019-10-02 09:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_department', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=5, unique=True)),
                ('status', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_group', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident_number', models.CharField(blank=True, max_length=255)),
                ('name_lastname', models.CharField(blank=True, max_length=255)),
                ('sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('age', models.IntegerField(blank=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('department', models.ForeignKey(default='CenterID', on_delete=django.db.models.deletion.PROTECT, to='question_app.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=500)),
                ('number', models.IntegerField(unique=True)),
                ('score', models.IntegerField()),
                ('category', models.ForeignKey(default='Category', on_delete=django.db.models.deletion.PROTECT, to='question_app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale', models.CharField(choices=[('Scale 1', 'Scale 1'), ('Scale 2', 'Scale 2'), ('Scale 3', 'Scale 3')], max_length=10)),
                ('q2_number', models.IntegerField(default='0')),
                ('key', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_app.Question')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='question_app.Group'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', models.CharField(max_length=20)),
                # ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_app.Question')),
                ('user', models.ForeignKey(default='User', on_delete=django.db.models.deletion.PROTECT, to='question_app.UserInformation')),
            ],
        ),
    ]
