# Generated by Django 2.2.2 on 2019-10-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_app', '0002_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='ans',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
