# Generated by Django 2.2.2 on 2019-10-14 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_app', '0003_auto_20191002_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='question_app.Group')),
                ('user', models.ForeignKey(default='User', on_delete=django.db.models.deletion.PROTECT, to='question_app.UserInformation')),
            ],
        ),
    ]
